// Generated by CoffeeScript 1.6.2
var inHours;

inHours = function(start, end) {
  var _ref;

  if ((start <= (_ref = new Date().getHours()) && _ref < end)) {
    return true;
  } else {
    return false;
  }
};
